### PR TITLE
Use Ghostscript to merge page files (BL-9059)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18)

### CODE REVIEW

**Review by StephenMcConnel — CHANGES_REQUESTED** [review]
One comment on one of your code comments.
One question in addition: have you compared the size of the output file with and without the "time saver" option?  I'm just curious.  I don't think there should be a significant difference.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18#-:-MIuNK-O5pOX8UgYxlAm:b-fnru6l)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[src/GeckofxHtmlToPDFComponent.cs, line 378 at r1](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18#-MIuM9CN9MCR7GV2FuWq:-MIuM9CO30IdY99UItLe:b-gtnjbm) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/97055dd7b510724b0554add177042cdc9b1146ae/src/GeckofxHtmlToPDFComponent.cs#L378)):*
> ```Smalltalk
> 		{
> 			// We previously did this using PdfSharp, but could not get the memory usage reasonable for large
> 			// files. So now we run ghostscript.
> ```

I would make the comment a bit more explicit by adding "in the same process" after PdfSharp and "in a separate process" after ghostscript.

**Review by StephenMcConnel — COMMENTED** [review]
Otherwise, the code looks okay.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18#-:-MIuNs56CWK_y-UtW0nT:b17jjxp)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
I attempted the comparison, but for the book in question in this project, Bloom was not able to make the PDF at all without the reduced memory setting.

> *[Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18#-:-MIufbec5A09nGCPnxOC:brd5jd2)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @andrew-polk and @StephenMcConnel)

___
*[src/GeckofxHtmlToPDFComponent.cs, line 378 at r1](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18#-MIuM9CN9MCR7GV2FuWq:-MIucUQa0-cCov0JsoIa:b-896fix) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/97055dd7b510724b0554add177042cdc9b1146ae/src/GeckofxHtmlToPDFComponent.cs#L378)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I would make the comment a bit more explicit by adding "in the same process" after PdfSharp and "in a separate process" after ghostscript.
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18)* status: all files reviewed, 1 unresolved discussion (waiting on @StephenMcConnel)

**Review by andrew-polk — APPROVED** [review]
> Dismissed @StephenMcConnel from a discussion.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/18)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
