### PR TITLE
Add single page mode for output (BL-3929)

### PR DESCRIPTION
**Pull request by StephenMcConnel**
Also add memory use check.

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/1)

### CODE REVIEW

**Comment by andrew-polk** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/GeckofxHtmlToPDFComponent.cs, line 278 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZG5qO6akqvDr7OFSO:-KWZG5qO6akqvDr7OFSP:buaifx9) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L278)):_

> /_hopefully nulls ok_/

And if not?

---

_[src/GeckofxHtmlToPDFComponent.cs, line 335 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZF1A-Nil8_sPNqh1W:-KWZF1A-Nil8_sPNqh1X:b6rx565) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L335)):_

> ``` Smalltalk
>           }
>           // Otherwise, nonexistent pages off the end of the book produce very small identical empty page files.
>           // (For Geckofx45, these empty page files are 833 bytes on Linux and 843 bytes on Windows.)
> ```

What happens if the next version of Geckofx produces these files of size 875?

---

_[src/GeckofxHtmlToPDFComponent.cs, line 388 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZEjP78DMQGozXEk9x:-KWZEjP78DMQGozXEk9y:b-kyqk2e) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L388)):_

> ``` Smalltalk
>                   filenames.Add(file.FullName);
>           }
>           filenames.Sort();
> ```

Is this going to sort as 1, 10, 2, 3, etc?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1)_

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

_[src/GeckofxHtmlToPDFComponent.cs, line 278 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZG5qO6akqvDr7OFSO:-KWZQpigu5N6k4Wjmhlz:b-cug6jv) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L278)):_
<details><summary>

<i>Previously, andrew-polk wrote…</i></summary>



> > /_hopefully nulls ok_/
> 
> And if not?
> </details>
> The code works okay as far as I can tell.  It was copied verbatim from an email from Tom Hindle, who may have writing off the top of his head.  Looking at the arguments in the Geckofx sources, I think it's an optional logger object that is being passed null.

---

_[src/GeckofxHtmlToPDFComponent.cs, line 335 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZF1A-Nil8_sPNqh1W:-KWZRCf8nQGH02Ank9lJ:b-knl7bi) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L335)):_
<details><summary>

<i>Previously, andrew-polk wrote…</i></summary>



> What happens if the next version of Geckofx produces these files of size 875?
> </details>
> When we test the program with a new version using the --single-pages option, it will never terminate.  The programmer should become suspicious somewhere around page 3000, and notice that there are 2900 files with same exact size of 875.  :-)  That's how I came up with this number to begin with since my original code assumed a final file size of zero.

---

_[src/GeckofxHtmlToPDFComponent.cs, line 388 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZEjP78DMQGozXEk9x:-KWZRaz9XdTQyUn4ju3H:b-vrqeaa) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L388)):_
<details><summary>

<i>Previously, andrew-polk wrote…</i></summary>



> Is this going to sort as 1, 10, 2, 3, etc?
> </details>
> It may sort as 001..100, 1000, 10000, 101, etc.  I don't expect more than 999 pages in any plausible Bloom book.  I suppose i could change the format to {1:0000} from {1:000} where the filenames are being created.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1)_

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

_[src/GeckofxHtmlToPDFComponent.cs, line 335 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZF1A-Nil8_sPNqh1W:-KWZSeXvVnvEBjSHBPge:b5398h3) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L335)):_
<details><summary>

<i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary>



> When we test the program with a new version using the --single-pages option, it will never terminate.  The programmer should become suspicious somewhere around page 3000, and notice that there are 2900 files with same exact size of 875.  :-)  That's how I came up with this number to begin with since my original code assumed a final file size of zero.
> </details>
> I guess I'm just concerned that this feature could easily get missed in testing when we upgrade versions of Geckofx

---

_[src/GeckofxHtmlToPDFComponent.cs, line 388 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZEjP78DMQGozXEk9x:-KWZSuwaRYPX1mc02kX1:bt4kit6) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L388)):_
<details><summary>

<i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary>



> It may sort as 001..100, 1000, 10000, 101, etc.  I don't expect more than 999 pages in any plausible Bloom book.  I suppose i could change the format to {1:0000} from {1:000} where the filenames are being created.
> </details>
> No, <=999 should be okay. I missed the connection of formatting as 1:000. Thanks for clarifying.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1)_

**Comment by StephenMcConnel** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/GeckofxHtmlToPDFComponent.cs, line 335 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZF1A-Nil8_sPNqh1W:-KWZUb1nd_ar95U4I3sL:b-er3h2u) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L335)):_
<details><summary>

<i>Previously, andrew-polk wrote…</i></summary>



> I guess I'm just concerned that this feature could easily get missed in testing when we upgrade versions of Geckofx
> </details>
> There's the flip side that genuine blank pages from Bloom are only ~950 bytes long.  I doubt someone would leave 5 consecutive pages blank, but it could possibly happen.  And those files are likelier to get shorter than the bogus empty pages get longer.  I could add a couple of test scripts to exercise the program on the test data with differing command line options including --single-pages.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1)_

**Comment by andrew-polk** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[src/GeckofxHtmlToPDFComponent.cs, line 335 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZF1A-Nil8_sPNqh1W:-KWZWUadPPafRQPvk5RQ:b-70qffq) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L335)):_
<details><summary>

<i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary>



> There's the flip side that genuine blank pages from Bloom are only ~950 bytes long.  I doubt someone would leave 5 consecutive pages blank, but it could possibly happen.  And those files are likelier to get shorter than the bogus empty pages get longer.  I could add a couple of test scripts to exercise the program on the test data with differing command line options including --single-pages.
> </details>
> Seems like a good idea if not terribly time-consuming.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1)_

**Comment by StephenMcConnel** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[src/GeckofxHtmlToPDFComponent.cs, line 335 at r1](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-KWZF1A-Nil8_sPNqh1W:-KWZhlPFQk0x1IYZDDjj:b-896fix) ([raw file](https://github.com/bloombooks/geckofxhtmltopdf/blob/d2664d6d56ce6e0093d88289110f195547a2f44b/src/GeckofxHtmlToPDFComponent.cs#L335)):_
<details><summary>

<i>Previously, andrew-polk wrote…</i></summary>



> Seems like a good idea if not terribly time-consuming.
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1)_

**Comment by andrew-polk** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/1#-:-KWZk_qBnjAIRCXwMcPh:bnfp4nl)_

**Pull request merged**
