### PR TITLE
Update from Geckofx 45.0.19 to 45.0.28 for Windows and target .NET 4.5 (BL-4166)

### PR DESCRIPTION
**Pull request by andrew-polk**
Also moved version number to 1.2

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/geckofxhtmltopdf/3)

### CODE REVIEW

**Comment by JohnThomson** [comment]
:lgtm: (though I don't know what the new Prefer32bit false lines do), but I asked SteveMc to check it doesn't break Linux since that has a distinct build process.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/3#-:-KaiXuSjF81kq2pHouTy:b-ajro6a)*

**Comment by JohnThomson** [comment]
Steve says it's OK as long as all the changes are in the NT-only sections, but should create an issue to update the Linux build to latest GeckoFx.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/3#-:-KaiYEmKowS8yaqARMAP:b-amsvz5)*

**Comment by andrew-polk** [comment]
Those were auto-generated, and I don't know their significance, either. Since they don't seem to be exclusive to Windows builds, I will remove them.
I will create an issue to do the upgrade for Linux.

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/3#-:-Kall1ssNhZhxBb2HtXv:b-4ecdm4)*

**Comment by andrew-polk** [comment]
Removed extraneous lines and created BL-4198

---

Review status: 3 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/bloombooks/geckofxhtmltopdf/3#-:-Kaln4eblHVb7W8Eux27:b-e1mg54)*

**Pull request merged**
